language: java
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz
  - sudo apt-get install -y doxygen
notifications:
  email:
  - hartmut_juergens@yahoo.de
cache:
  directories:
  - .autoconf
  - $HOME/.m2